backend: 
    name: github

media_folder: static/assets

collections: 
    - name: post
      label: Posts
      folder: src/Posts
      create: true
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Body", name: "body", widget: "markdown"}